---
server:
    install: "1"
    packages: [htop, git, mc]
    timezone: Europe/Kiev
    locale: en_US.UTF-8
    domain: "stepic.lan"
vagrant_local:
    install: "1"
    vm:
        hostname: "{{server.domain}}"

nginx_sendfile: "off"

mysql_user_home: "/home/box"
mysql_root_password: ""

mysql_packages:
    - mysql-common-5.6
    - mysql-server-5.6

mysql_databases:
    - { name: "ask" }

mysql_users:
    - { name: "ask", password: "ask" }